apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafka-producer-climate-service
  name: kafka-producer-climate-service
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  selector:
    matchLabels:
      app: kafka-producer-climate-service
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-producer-climate-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: airthings-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: airthings-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                  key: CLIENT_SECRET
          name: kafka-producer-climate-service
          image: oyvindis/kafka-producer-climate-service
          imagePullPolicy: Always
      restartPolicy: Always
