spring:

  security:
    oauth2:
      client:
        registration:
          airthings:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
            clientAuthenticationMethod: client_secret_post
            authorizationGrantType: client_credentials
            scopes: read:device:current_values
            clientName: ois-airthings
        provider:
          airthings:
            authorizationUri: https://accounts.airthings.com/authorize
            tokenUri: https://accounts-api.airthings.com/v1/token
